export const LF2_PROOF_REVIEW_APPROVE_CONFIRMATION = "APPROVE ONE META PROOF";
export const LF2_PROOF_REVIEW_REJECT_CONFIRMATION = "REJECT ONE META PROOF";
export const LF2_PROOF_REVIEW_REVOKE_CONFIRMATION = "REVOKE META PROOF APPROVAL";

export const LF2_PROOF_REVIEW_ALLOWED_CANONICAL_LANE = "facebook_meta_lead_ads";
export const LF2_PROOF_REVIEW_ALLOWED_POLICY_KEY = "meta_lead_ads";
