export const LEADCAPTURE_TRUST_PILOT_CLIENT_ACCOUNT_ID = "vet_life_james_torrey";
export const LEADCAPTURE_TRUST_PILOT_CAMPAIGN_KEY = "LCIO_LEGACY_VET_LIFE_JAMES_TORREY_VET_FEX";
export const LEADCAPTURE_TRUST_PILOT_FORM_ID = "23381";
export const LEADCAPTURE_TRUST_PILOT_PROVIDER = "leadcapture_io";
export const LEADCAPTURE_TRUST_PILOT_SOURCE_LANE = "leadcapture_io";

export const LEADCAPTURE_TRUST_ATTACH_CONFIRMATION =
  "ATTACH ONE LEADCAPTURE TRUST FORM";

export const LEADCAPTURE_TRUST_IDENTITY_MATCH_WINDOW_MS = 15 * 60 * 1000;
export const LEADCAPTURE_TRUST_RECONCILE_MAX_RECORDS = 25;
