#!/usr/bin/env bash
#
# Cloud Agent install phase for SA360.
#
# Runs once after checkout to produce durable, reusable state:
#   - local Postgres + Redis system packages (best effort, guarded)
#   - workspace dependencies from the pinned pnpm lockfile
#   - Prisma client generation (source-derived)
#   - the @sa360/shared build that other apps compile against
#   - a localhost-only .env for dev/test (never committed)
#
# It is idempotent and MUST NOT start long-running servers, run migrations
# against any remote database, or deploy anything. Per-boot service startup and
# local schema application live in scripts/cloud-agent-start.sh.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

log() { printf '\n[cloud-install] %s\n' "$*"; }

# 1) System services used by local dev + the API test suite (Postgres, Redis).
#    Best effort: if apt/sudo are unavailable the workspace still installs and
#    builds; only DB/Redis-backed API tests become unavailable.
if command -v apt-get >/dev/null 2>&1 && command -v sudo >/dev/null 2>&1; then
  if ! command -v psql >/dev/null 2>&1 || ! command -v redis-server >/dev/null 2>&1; then
    log "installing PostgreSQL + Redis (system packages)"
    sudo apt-get update -y
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      postgresql postgresql-contrib redis-server
  else
    log "PostgreSQL + Redis already installed"
  fi
else
  log "apt-get/sudo unavailable; skipping DB/Redis install (DB-backed API tests will be unavailable)"
fi

# 2) Ensure the repository-pinned pnpm (packageManager) is active.
corepack enable >/dev/null 2>&1 || true

# 3) Workspace dependencies, strictly from the committed lockfile.
log "pnpm install --frozen-lockfile"
pnpm install --frozen-lockfile

# 4) Prisma client generation (source-derived, reusable).
log "pnpm prisma:generate"
pnpm prisma:generate

# 5) Build the shared package that the API, worker, and admin-coc depend on.
log "building @sa360/shared"
pnpm --filter @sa360/shared build

# 6) Localhost-only dev/test env file. Created once; an existing .env is left
#    untouched. These values only ever point at 127.0.0.1 services.
if [ ! -f .env ]; then
  log "writing default .env (localhost dev/test config)"
  cat > .env <<'ENV'
# Auto-generated by scripts/cloud-agent-install.sh for local Cloud Agent dev/testing.
# LOCAL ONLY. Never repoint these at staging or production.
DATABASE_URL=postgresql://sa360:sa360password@127.0.0.1:5432/sa360
REDIS_URL=redis://127.0.0.1:6379
# API Prisma-backed tests only honor SA360_TEST_DATABASE_URL and require a
# localhost host with a database name containing "test".
SA360_TEST_DATABASE_URL=postgresql://sa360:sa360password@127.0.0.1:5432/sa360_test
SA360_TEST_REDIS_URL=redis://127.0.0.1:6379
NODE_ENV=development
ENV
else
  log ".env already present; leaving it untouched"
fi

log "install complete"
