import type { TimezoneKey, TimezoneStatus } from "./inventory-types";

/** Geographic timezone metadata (not inventory counts). */
export const STATE_TIMEZONE_META: Record<
  string,
  { timezones: TimezoneKey[]; timezoneStatus: TimezoneStatus; stateName: string }
> = {
  AL: { stateName: "Alabama", timezones: ["Central"], timezoneStatus: "single" },
  AK: { stateName: "Alaska", timezones: ["Pacific"], timezoneStatus: "single" },
  AZ: { stateName: "Arizona", timezones: ["Mountain"], timezoneStatus: "single" },
  AR: { stateName: "Arkansas", timezones: ["Central"], timezoneStatus: "single" },
  CA: { stateName: "California", timezones: ["Pacific"], timezoneStatus: "single" },
  CO: { stateName: "Colorado", timezones: ["Mountain"], timezoneStatus: "single" },
  CT: { stateName: "Connecticut", timezones: ["Eastern"], timezoneStatus: "single" },
  DE: { stateName: "Delaware", timezones: ["Eastern"], timezoneStatus: "single" },
  DC: { stateName: "District of Columbia", timezones: ["Eastern"], timezoneStatus: "single" },
  FL: { stateName: "Florida", timezones: ["Eastern", "Central"], timezoneStatus: "mixed" },
  GA: { stateName: "Georgia", timezones: ["Eastern"], timezoneStatus: "single" },
  HI: { stateName: "Hawaii", timezones: ["Pacific"], timezoneStatus: "single" },
  ID: { stateName: "Idaho", timezones: ["Mountain", "Pacific"], timezoneStatus: "mixed" },
  IL: { stateName: "Illinois", timezones: ["Central"], timezoneStatus: "single" },
  IN: { stateName: "Indiana", timezones: ["Eastern", "Central"], timezoneStatus: "mixed" },
  IA: { stateName: "Iowa", timezones: ["Central"], timezoneStatus: "single" },
  KS: { stateName: "Kansas", timezones: ["Central", "Mountain"], timezoneStatus: "mixed" },
  KY: { stateName: "Kentucky", timezones: ["Eastern", "Central"], timezoneStatus: "mixed" },
  LA: { stateName: "Louisiana", timezones: ["Central"], timezoneStatus: "single" },
  ME: { stateName: "Maine", timezones: ["Eastern"], timezoneStatus: "single" },
  MD: { stateName: "Maryland", timezones: ["Eastern"], timezoneStatus: "single" },
  MA: { stateName: "Massachusetts", timezones: ["Eastern"], timezoneStatus: "single" },
  MI: { stateName: "Michigan", timezones: ["Eastern", "Central"], timezoneStatus: "mixed" },
  MN: { stateName: "Minnesota", timezones: ["Central"], timezoneStatus: "single" },
  MS: { stateName: "Mississippi", timezones: ["Central"], timezoneStatus: "single" },
  MO: { stateName: "Missouri", timezones: ["Central"], timezoneStatus: "single" },
  MT: { stateName: "Montana", timezones: ["Mountain"], timezoneStatus: "single" },
  NE: { stateName: "Nebraska", timezones: ["Central", "Mountain"], timezoneStatus: "mixed" },
  NV: { stateName: "Nevada", timezones: ["Pacific", "Mountain"], timezoneStatus: "mixed" },
  NH: { stateName: "New Hampshire", timezones: ["Eastern"], timezoneStatus: "single" },
  NJ: { stateName: "New Jersey", timezones: ["Eastern"], timezoneStatus: "single" },
  NM: { stateName: "New Mexico", timezones: ["Mountain"], timezoneStatus: "single" },
  NY: { stateName: "New York", timezones: ["Eastern"], timezoneStatus: "single" },
  NC: { stateName: "North Carolina", timezones: ["Eastern"], timezoneStatus: "single" },
  ND: { stateName: "North Dakota", timezones: ["Central", "Mountain"], timezoneStatus: "mixed" },
  OH: { stateName: "Ohio", timezones: ["Eastern"], timezoneStatus: "single" },
  OK: { stateName: "Oklahoma", timezones: ["Central"], timezoneStatus: "single" },
  OR: { stateName: "Oregon", timezones: ["Pacific", "Mountain"], timezoneStatus: "mixed" },
  PA: { stateName: "Pennsylvania", timezones: ["Eastern"], timezoneStatus: "single" },
  RI: { stateName: "Rhode Island", timezones: ["Eastern"], timezoneStatus: "single" },
  SC: { stateName: "South Carolina", timezones: ["Eastern"], timezoneStatus: "single" },
  SD: { stateName: "South Dakota", timezones: ["Central", "Mountain"], timezoneStatus: "mixed" },
  TN: { stateName: "Tennessee", timezones: ["Eastern", "Central"], timezoneStatus: "mixed" },
  TX: { stateName: "Texas", timezones: ["Central", "Mountain"], timezoneStatus: "mixed" },
  UT: { stateName: "Utah", timezones: ["Mountain"], timezoneStatus: "single" },
  VT: { stateName: "Vermont", timezones: ["Eastern"], timezoneStatus: "single" },
  VA: { stateName: "Virginia", timezones: ["Eastern"], timezoneStatus: "single" },
  WA: { stateName: "Washington", timezones: ["Pacific"], timezoneStatus: "single" },
  WV: { stateName: "West Virginia", timezones: ["Eastern"], timezoneStatus: "single" },
  WI: { stateName: "Wisconsin", timezones: ["Central"], timezoneStatus: "single" },
  WY: { stateName: "Wyoming", timezones: ["Mountain"], timezoneStatus: "single" },
};
